#!/usr/bin/env bash
# This file only has "alias" declarations of one command

# Base mods to commands
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ssh='ssh -Y'

# Shorthands
alias ll='ls -al'

# Going up?
alias ..='cd ..'
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..7='cd ../../../../../../..'
alias ..8='cd ../../../../../../../..'
alias ..9='cd ../../../../../../../../..'

# Typo aliases
alias s='ls'
alias l='ls'
alias sl='ls'
alias d='cd'
alias c='cd'
alias dc='cd'
