#!/usr/bin/env bash
# These are my mods to the prompt

# Set the prompt command
_zlentz_prompt(){
  PS1="$(_prompt_env)$(_prompt_norm)$(_prompt_git)$(_prompt_ender)"
}
export PROMPT_COMMAND=_zlentz_prompt

# Built-in settings
export PROMPT_DIRTRIM=2

# Utilities #
# colors: define colors for use in all the prompts
# I stole these from bash-it
prompt_color_on(){
  export black="\[\e[0;30m\]"
  export red="\[\e[0;31m\]"
  export green="\[\e[0;32m\]"
  export yellow="\[\e[0;33m\]"
  export blue="\[\e[0;34m\]"
  export purple="\[\e[0;35m\]"
  export cyan="\[\e[0;36m\]"
  export white="\[\e[0;37m\]"
  export orange="\[\e[0;91m\]"
  export normal="\[\e[0m\]"
}

prompt_color_off(){
  unset black
  unset red
  unset green
  unset yellow
  unset blue
  unset purple
  unset cyan
  unset white
  unset orange
  unset normal
}

# Special stuff #
# git: show git repo info if we're in a repo
prompt_git_on(){
  export PROMPT_GIT=1
}

prompt_git_off(){
  unset PROMPT_GIT
}

_prompt_git(){
  if [[ -n "${PROMPT_GIT}" ]]; then
    if [[ -x "$(command -v git)" ]]; then
      if git rev-parse --git-dir > /dev/null 2>&1; then
        if [[ -n "$(git status --porcelain)" ]]; then
          status_symbol=${red}"+"
        else
          status_symbol=${green}"-"
        fi
        echo "(${purple}$(git symbolic-ref -q --short HEAD) ${status_symbol}${normal})"
      fi
    fi
  fi
}

# env: allow us to change our path quickly
prompt_env_on(){
  export PROMPT_ENV=1
}

prompt_env_off(){
  unset PROMPT_ENV
}

_prompt_env(){
  if [[ -n "${PROMPT_ENV}" ]]; then
    if [[ -n "${ENVNAME}" ]]; then
      echo "(${purple}${ENVNAME}${normal})"
    elif [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
      echo "(${purple}${CONDA_DEFAULT_ENV}${normal})"
    fi
  fi
}

# Ordinary stuff
# user: show our username
prompt_user_on(){
  export PROMPT_USER=1
}

prompt_user_off(){
  unset PROMPT_USER
}

# host: show the hostname
prompt_host_on(){
  export PROMPT_HOST=1
}

prompt_host_off(){
  unset PROMPT_HOST
}

# path: show the current working directory
prompt_path_on(){
  export PROMPT_PATH=1
}

prompt_path_off(){
  unset PROMPT_PATH
}

# newline: add a \n when we want it
prompt_newline_on(){
  export PROMPT_NEWLINE=1
}

prompt_newline_off(){
  unset PROMPT_NEWLINE
}

# group the boring stuff together
_prompt_norm(){
  if [[ -n "${PROMPT_USER}" ]]; then
    echo -n "${cyan}\u"
  fi
  if [[ -n "${PROMPT_HOST}" ]]; then
    if [[ -n "${PROMPT_USER}" ]]; then
      echo -n "@"
    else
      echo -n "${cyan}"
    fi
    echo -n "\h"
  fi
  echo -n "${normal}"
  if [[ -n "${PROMPT_PATH}" ]]; then
    echo ":${green}\w${normal}"
  fi
}

# Last, just have the $ with or without the newline
_prompt_ender(){
  if [[ -n "${PROMPT_NEWLINE}" ]]; then
    echo -n "\n"
  fi
  echo "$ "
}

# Some preset combinations of options
prompt_full(){
  prompt_git_on
  prompt_env_on
  prompt_user_on
  prompt_host_on
  prompt_path_on
  prompt_newline_off
}

prompt_simple(){
  prompt_git_off
  prompt_env_off
  prompt_user_on
  prompt_host_on
  prompt_path_on
  prompt_newline_off
}

prompt_short(){
  prompt_git_off
  prompt_env_off
  prompt_user_on
  prompt_host_on
  prompt_path_off
  prompt_newline_off
}

prompt_none(){
  prompt_git_off
  prompt_env_off
  prompt_user_off
  prompt_host_off
  prompt_path_off
  prompt_newline_off
}

# Turn on the prompt!
prompt_full
prompt_color_on
